import type { ExpoConfig } from 'expo/config';

/**
 * Native configuration. The two non-negotiable bits for a LAN companion app:
 *  - Local-network access (iOS prompts for it on any access to a private IP, e.g. the subnet scan)
 *  - Cleartext HTTP to RFC1918 addresses (SillyTavern is http:// on the LAN by default)
 *
 * `NSAllowsLocalNetworking` permits http to local hosts without opening up arbitrary cleartext
 * (App-Store friendly, and tighter than NSAllowsArbitraryLoads).
 */
const config: ExpoConfig = {
  name: 'SillyTavern Companion',
  slug: 'sillytavern-companion',
  scheme: 'stcompanion',
  version: '0.9.1',
  orientation: 'portrait',
  userInterfaceStyle: 'dark',
  // New Architecture is the default (and only) arch on SDK 56 / RN 0.85, so an explicit
  // `newArchEnabled: true` is redundant - and it isn't in this Expo version's config types.
  assetBundlePatterns: ['**/*'],
  icon: './assets/icon.png',
  ios: {
    supportsTablet: true,
    bundleIdentifier: 'de.tiretask.stcompanion',
    infoPlist: {
      NSLocalNetworkUsageDescription:
        'Sucht im lokalen WLAN nach deiner laufenden SillyTavern-Instanz, um sich zu verbinden.',
      NSAppTransportSecurity: {
        NSAllowsLocalNetworking: true,
      },
    },
  },
  android: {
    package: 'de.tiretask.stcompanion',
    versionCode: 3,
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      monochromeImage: './assets/adaptive-icon-monochrome.png',
      backgroundColor: '#0B0B0F',
    },
    permissions: ['android.permission.INTERNET'],
  },
  plugins: [
    'expo-router',
    'expo-font',
    'expo-secure-store',
    'expo-localization',
    [
      'expo-splash-screen',
      {
        image: './assets/splash-icon.png',
        imageWidth: 200,
        resizeMode: 'contain',
        backgroundColor: '#0B0B0F',
        dark: { image: './assets/splash-icon.png', backgroundColor: '#0B0B0F' },
      },
    ],
    // Injects a `release` signingConfig that reads STC_UPLOAD_* from env/gradle properties
    // (android/ is gitignored and regenerated by prebuild, so signing must flow through here).
    './plugins/withReleaseSigning',
    [
      'expo-image-picker',
      {
        photosPermission: 'Erlaubt das Anhängen von Bildern an Nachrichten (für Vision-Modelle).',
      },
    ],
    [
      'expo-build-properties',
      {
        android: {
          // Allow http:// to the LAN. A network_security_config.xml scoped to RFC1918 would be
          // tighter; usesCleartextTraffic is the pragmatic v1 default.
          usesCleartextTraffic: true,
        },
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
  },
};

export default config;
