import type { ExpoConfig } from 'expo/config';

// R8 keep rules for native libs WITHOUT consumer proguard files (verified: keyboard-controller
// 1.21.6 ships none; gesture-handler/screens/safe-area-context are belt-and-braces and can be
// dropped once a minified build has soaked). expo-* modules are covered by expo-modules-core's
// comprehensive consumer rules.
const EXTRA_PROGUARD_RULES = `
-keep class com.reactnativekeyboardcontroller.** { *; }
-keep class com.swmansion.gesturehandler.** { *; }
-keep class com.swmansion.rnscreens.** { *; }
-keep class com.th3rdwave.safeareacontext.** { *; }
-dontwarn org.bouncycastle.**
-dontwarn org.conscrypt.**
-dontwarn org.openjsse.**
`;

/**
 * Native configuration. The two non-negotiable bits for a LAN companion app:
 *  - Local-network access (iOS prompts for it on any access to a private IP, e.g. the subnet scan)
 *  - Cleartext HTTP to RFC1918 addresses (SillyTavern is http:// on the LAN by default)
 *
 * `NSAllowsLocalNetworking` permits http to local hosts without opening up arbitrary cleartext
 * (App-Store friendly, and tighter than NSAllowsArbitraryLoads).
 */
const config: ExpoConfig = {
  name: 'SillyTavern Companion',
  slug: 'sillytavern-companion',
  scheme: 'stcompanion',
  version: '0.14.1',
  orientation: 'portrait',
  userInterfaceStyle: 'dark',
  // New Architecture is the default (and only) arch on SDK 56 / RN 0.85, so an explicit
  // `newArchEnabled: true` is redundant - and it isn't in this Expo version's config types.
  assetBundlePatterns: ['**/*'],
  icon: './assets/icon.png',
  ios: {
    supportsTablet: true,
    bundleIdentifier: 'de.tiretask.stcompanion',
    infoPlist: {
      NSLocalNetworkUsageDescription:
        'Sucht im lokalen WLAN nach deiner laufenden SillyTavern-Instanz, um sich zu verbinden.',
      NSAppTransportSecurity: {
        NSAllowsLocalNetworking: true,
      },
    },
  },
  android: {
    package: 'de.tiretask.stcompanion',
    versionCode: 12,
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      monochromeImage: './assets/adaptive-icon-monochrome.png',
      backgroundColor: '#0B0B0F',
    },
    // REQUEST_INSTALL_PACKAGES: in-app self-update hands the downloaded release APK
    // to the system installer (user still confirms every install).
    permissions: ['android.permission.INTERNET', 'android.permission.REQUEST_INSTALL_PACKAGES'],
  },
  plugins: [
    'expo-router',
    'expo-font',
    'expo-secure-store',
    'expo-localization',
    [
      'expo-splash-screen',
      {
        image: './assets/splash-icon.png',
        imageWidth: 200,
        resizeMode: 'contain',
        backgroundColor: '#0B0B0F',
        dark: { image: './assets/splash-icon.png', backgroundColor: '#0B0B0F' },
      },
    ],
    // Injects a `release` signingConfig that reads STC_UPLOAD_* from env/gradle properties
    // (android/ is gitignored and regenerated by prebuild, so signing must flow through here).
    './plugins/withReleaseSigning',
    // Extra gradle.properties (art-profile rewrite breaks under R8 with RN's baseline profile).
    './plugins/withGradleProps',
    [
      'expo-image-picker',
      {
        photosPermission: 'Erlaubt das Anhängen von Bildern an Nachrichten (für Vision-Modelle).',
      },
    ],
    [
      'expo-local-authentication',
      {
        faceIDPermission: 'Entsperrt die App per Face ID, wenn die App-Sperre aktiviert ist.',
      },
    ],
    [
      'expo-build-properties',
      {
        android: {
          // Allow http:// to the LAN. A network_security_config.xml scoped to RFC1918 would be
          // tighter; usesCleartextTraffic is the pragmatic v1 default.
          usesCleartextTraffic: true,
          // arm64-only: drops x86/x86_64 (39.4 MB) and armeabi-v7a (13.1 MB) native libs.
          // 32-bit-only phones are ~2014-era; re-add 'armeabi-v7a' here if needed (~+13 MB).
          // Emulator debug builds: gradlew ... "-PreactNativeArchitectures=x86_64"
          buildArchs: ['arm64-v8a'],
          enableMinifyInReleaseBuilds: true,
          enableShrinkResourcesInReleaseBuilds: true,
          extraProguardRules: EXTRA_PROGUARD_RULES,
        },
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
  },
};

export default config;
